
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /tmp/mysql.sock
  # 接続先を別コンテナのdbに設定
  host: db
  # MySQLのrootユーザーを使用
  username: root
  # コンテナ内の環境変数を展開した値をpasswordに設定
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>


development:
  <<: *default
  database: hosdx-rails_development

test:
  <<: *default
  database: hosdx-rails_test

production:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/mysqld/mysqld.sock
  # デプロイ先ではローカルへ
  host: localhost
  # MySQLのrootユーザーを使用
  username: hosdx
  # コンテナ内の環境変数を展開した値をpasswordに設定
  password: <%= ENV['MYSQL_USER_PASSWORD'] %>
  database: hosdx-rails_production
